version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - product-catalog-service
      - inventory-service
      - cart-service
      - order-service
      - notification-service
      - payment-service

  product-catalog-service:
    build: ./product-catalog-service
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=production

  inventory-service:
    build: ./inventory-service
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  cart-service:
    build: ./cart-service
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  order-service:
    build: ./order-service
    ports:
      - "4009:4009"
    environment:
      - NODE_ENV=production

  notification-service:
    build: ./notification-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production

  payment-service:
    build: ./payment-service
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
