version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - product-catalog-service
      - inventory-service
      - cart-service
      - order-service
      - notification-service
      - payment-service

  product-catalog-service:
    build: ./product-catalog-service
    ports:
      - "4004:4004"
    expose:
      - "4004"

  inventory-service:
    build: ./inventory-service
    ports:
      - "4000:4000"
    expose:
      - "4000"

  cart-service:
    build: ./cart-service
    ports:
      - "4005:4005"
    expose:
      - "4005"

  order-service:
    build: ./order-service
    ports:
      - "4009:4009"
    expose:
      - "4009"

  notification-service:
    build: ./notification-service
    ports:
      - "4001:4001"
    expose:
      - "4001"

  payment-service:
    build: ./payment-service
    ports:
      - "4003:4003"
    expose:
      - "4003"
