name: Build and Test

on:
  push:
    branches-ignore: [main, master]
  pull_request:
    branches-ignore: [main, master]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Verify backend builds
        run: |
          cd backend
          for d in */; do
            echo "Building $d..."
            cd $d
            npm ci
            npm run build || echo "No build script found, skipping..."
            cd ..
          done

      - name: Verify client builds
        run: |
          cd client
          npm run build

      - name: Run backend tests
        run: |
          cd backend
          npm test || echo "No test configuration found"

      - name: Run client tests
        run: |
          cd client
          npm test -- --watchAll=false || echo "No test configuration found"
